version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: basic_nodejs_app
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
