version: "3.9"
services:
  backend:
    build: .
    container_name: backend_service_container
    ports:
      - "3000:3000"
    expose:
      - 3000
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports: 
      - "80:80" #it will run and expose over my local computer at 80 and map in nginx 80 in container
    container_name: nginx_container
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
